name: Pulp CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs at 3:00 UTC daily
    - cron: '00 3 * * *'
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
jobs:
  helm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pre-reqs
        with:
          ingress-type: nodeport

      - uses: actions/checkout@v4

      - name: Install Pulp Operator
        run: |
          kubectl create ns pulp-operator-system
          kubectl config set-context --current --namespace=pulp-operator-system
          helm install --set namespace=pulp-operator-system pulp-operator helm-charts/chart

      - uses: actions/checkout@v4
        with:
          repository: pulp/pulp-operator
          ref: main

      - name: Create Pulp Operator CR
        run: |
          kubectl apply -f .ci/assets/kubernetes/pulp-admin-password.secret.yaml
          kubectl apply -f config/samples/simple.yaml

      - name: Check and wait pulp-operator deploy
        run: |
          journalctl --unit=pulp-operator -f &
          kubectl logs -f -l app.kubernetes.io/component=operator -c manager &
          kubectl wait --for condition=Pulp-Operator-Finished-Execution pulp/example-pulp --timeout=900s
        shell: bash

      - name: Test all components
        run: |
          .ci/scripts/pulp_tests.sh -m
        shell: bash
        env:
          PY_COLORS: '1'

      - name: Logs
        if: always()
        run: |
          .github/workflows/scripts/show_logs.sh
          helm list
        shell: bash
